# Form implementation generated from reading ui file '.\qtdesignfiles\ability_dialogue_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(557, 414)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.ability_dialogue_groupbox = QtWidgets.QGroupBox(parent=Form)
        self.ability_dialogue_groupbox.setTitle("")
        self.ability_dialogue_groupbox.setObjectName("ability_dialogue_groupbox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ability_dialogue_groupbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ability_name_label = QtWidgets.QLabel(parent=self.ability_dialogue_groupbox)
        self.ability_name_label.setObjectName("ability_name_label")
        self.verticalLayout.addWidget(self.ability_name_label)
        self.ability_name_edit = QtWidgets.QLineEdit(parent=self.ability_dialogue_groupbox)
        self.ability_name_edit.setObjectName("ability_name_edit")
        self.verticalLayout.addWidget(self.ability_name_edit)
        self.ability_description_label = QtWidgets.QLabel(parent=self.ability_dialogue_groupbox)
        self.ability_description_label.setObjectName("ability_description_label")
        self.verticalLayout.addWidget(self.ability_description_label)
        self.ability_description_edit = QtWidgets.QTextEdit(parent=self.ability_dialogue_groupbox)
        self.ability_description_edit.setObjectName("ability_description_edit")
        self.verticalLayout.addWidget(self.ability_description_edit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.apply_ability_pushbutton = QtWidgets.QPushButton(parent=self.ability_dialogue_groupbox)
        self.apply_ability_pushbutton.setObjectName("apply_ability_pushbutton")
        self.horizontalLayout.addWidget(self.apply_ability_pushbutton)
        self.delete_ability_pushbutton = QtWidgets.QPushButton(parent=self.ability_dialogue_groupbox)
        self.delete_ability_pushbutton.setObjectName("delete_ability_pushbutton")
        self.horizontalLayout.addWidget(self.delete_ability_pushbutton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.ability_dialogue_groupbox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ability_name_label.setText(_translate("Form", "Ability Name"))
        self.ability_description_label.setText(_translate("Form", "Description"))
        self.apply_ability_pushbutton.setText(_translate("Form", "Apply"))
        self.delete_ability_pushbutton.setText(_translate("Form", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
