# Form implementation generated from reading ui file '.\qtdesignfiles\ability_dialogue_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AbilityDialogueUi(object):
    def setupUi(self, AbilityDialogueUi):
        AbilityDialogueUi.setObjectName("AbilityDialogueUi")
        AbilityDialogueUi.resize(527, 419)
        self.gridLayout = QtWidgets.QGridLayout(AbilityDialogueUi)
        self.gridLayout.setObjectName("gridLayout")
        self.ability_dialogue_groupbox = QtWidgets.QGroupBox(parent=AbilityDialogueUi)
        self.ability_dialogue_groupbox.setTitle("")
        self.ability_dialogue_groupbox.setObjectName("ability_dialogue_groupbox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ability_dialogue_groupbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ability_name_label = QtWidgets.QLabel(parent=self.ability_dialogue_groupbox)
        self.ability_name_label.setObjectName("ability_name_label")
        self.verticalLayout.addWidget(self.ability_name_label)
        self.ability_name_edit = QtWidgets.QLineEdit(parent=self.ability_dialogue_groupbox)
        self.ability_name_edit.setObjectName("ability_name_edit")
        self.verticalLayout.addWidget(self.ability_name_edit)
        self.ability_description_label = QtWidgets.QLabel(parent=self.ability_dialogue_groupbox)
        self.ability_description_label.setObjectName("ability_description_label")
        self.verticalLayout.addWidget(self.ability_description_label)
        self.ability_description_edit = QtWidgets.QTextEdit(parent=self.ability_dialogue_groupbox)
        self.ability_description_edit.setObjectName("ability_description_edit")
        self.verticalLayout.addWidget(self.ability_description_edit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.apply_ability_pushbutton = QtWidgets.QPushButton(parent=self.ability_dialogue_groupbox)
        self.apply_ability_pushbutton.setObjectName("apply_ability_pushbutton")
        self.horizontalLayout.addWidget(self.apply_ability_pushbutton)
        self.delete_ability_pushbutton = QtWidgets.QPushButton(parent=self.ability_dialogue_groupbox)
        self.delete_ability_pushbutton.setObjectName("delete_ability_pushbutton")
        self.horizontalLayout.addWidget(self.delete_ability_pushbutton)
        self.cancel_ability_pushbutton = QtWidgets.QPushButton(parent=self.ability_dialogue_groupbox)
        self.cancel_ability_pushbutton.setObjectName("cancel_ability_pushbutton")
        self.horizontalLayout.addWidget(self.cancel_ability_pushbutton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.ability_dialogue_groupbox, 0, 0, 1, 1)

        self.retranslateUi(AbilityDialogueUi)
        QtCore.QMetaObject.connectSlotsByName(AbilityDialogueUi)

    def retranslateUi(self, AbilityDialogueUi):
        _translate = QtCore.QCoreApplication.translate
        AbilityDialogueUi.setWindowTitle(_translate("AbilityDialogueUi", "Dialog"))
        self.ability_name_label.setText(_translate("AbilityDialogueUi", "Ability Name"))
        self.ability_description_label.setText(_translate("AbilityDialogueUi", "Description"))
        self.apply_ability_pushbutton.setText(_translate("AbilityDialogueUi", "Apply"))
        self.delete_ability_pushbutton.setText(_translate("AbilityDialogueUi", "Delete"))
        self.cancel_ability_pushbutton.setText(_translate("AbilityDialogueUi", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AbilityDialogueUi = QtWidgets.QDialog()
    ui = Ui_AbilityDialogueUi()
    ui.setupUi(AbilityDialogueUi)
    AbilityDialogueUi.show()
    sys.exit(app.exec())
