# Form implementation generated from reading ui file '.\qtdesignfiles\gmbinder_convert_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GMBinderBrowser(object):
    def setupUi(self, GMBinderBrowser):
        GMBinderBrowser.setObjectName("GMBinderBrowser")
        GMBinderBrowser.resize(400, 300)
        self.gridLayout_2 = QtWidgets.QGridLayout(GMBinderBrowser)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(parent=GMBinderBrowser)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gmbinder_string_textbrowser = QtWidgets.QTextBrowser(parent=self.groupBox)
        self.gmbinder_string_textbrowser.setObjectName("gmbinder_string_textbrowser")
        self.gridLayout.addWidget(self.gmbinder_string_textbrowser, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(GMBinderBrowser)
        QtCore.QMetaObject.connectSlotsByName(GMBinderBrowser)

    def retranslateUi(self, GMBinderBrowser):
        _translate = QtCore.QCoreApplication.translate
        GMBinderBrowser.setWindowTitle(_translate("GMBinderBrowser", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GMBinderBrowser = QtWidgets.QDialog()
    ui = Ui_GMBinderBrowser()
    ui.setupUi(GMBinderBrowser)
    GMBinderBrowser.show()
    sys.exit(app.exec())
